package:
  name: pytorch-3dunet
  version: {{ RELEASE_VERSION }}

source:
  path: ..

build:
  noarch: python
  entry_points:
    - predict3dunet = pytorch3dunet.predict:main
    - train3dunet = pytorch3dunet.train:main

requirements:
  build:
    - python 3.8
    - setuptools

  run:
    - python
    - pytorch
    - tensorboard
    # workaround the issue https://github.com/pytorch/pytorch/pull/69904
    - setuptools 59.5.0
    - h5py
    - scipy
    - scikit-image
    - pyyaml

test:
  imports:
    - pytorch3dunet
    - pytorch3dunet.unet3d
    - pytorch3dunet.augment
    - pytorch3dunet.datasets
  requires:
    - pytest
  run:
    - py.test

about:
  home: https://github.com/wolny/pytorch-3dunet
  license: MIT
